require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'fast' do
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
   pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'

    pod 'iOSPhotoEditor', :git => 'https://github.com/prscX/photo-editor', :branch => 'master'
    permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
    pod 'Permission-Camera', :path =>  "#{permissions_path}/Camera"

  
    use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

    # Follow [Flipper iOS Setup Guidelines](https://fbflipper.com/docs/getting-started/ios-native)
    # This is required because iOSPhotoEditor is implemented using Swift and we have to use use_frameworks! in Podfile
 
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
    pod 'react-native-blob-util', :path => '../node_modules/react-native-blob-util'

    pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'
    
    pod 'Reachability'


    pod 'react-native-signature-capture', :path => '../node_modules/react-native-signature-capture'

    pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
    pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

    post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
